export const CODECUT_GENERATED_FILE_MARKER =
  "// Generated by Codecut. Do not edit.";

const OPENCODE_PLUGIN_PATH = ".opencode/plugins/codecut.js";

export function isCodecutOpenCodePlugin(source: string): boolean {
  return (
    source.includes(CODECUT_GENERATED_FILE_MARKER) &&
    source.includes('"hook", "--agent", "opencode"')
  );
}

export function isCodecutManagedGeneratedPath(filePath: string): boolean {
  return filePath.replaceAll("\\", "/") === OPENCODE_PLUGIN_PATH;
}

export function isCodecutManagedGeneratedFile(
  filePath: string,
  source: string,
): boolean {
  return (
    isCodecutManagedGeneratedPath(filePath) &&
    isCodecutOpenCodePlugin(source)
  );
}
